services:
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    hostname: airflow
    command: airflow 
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
